# Generated by Django 3.0.2 on 2020-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
