# Generated by Django 3.0.2 on 2020-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_ext',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
