# Generated by Django 3.0.2 on 2020-03-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200328_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
